language: node_js

node_js:
  - node
  - '7'
  - '8'

branches:
  only:
    - master

before_script:
  - npm install -g jest
  - npm install -g coveralls

script:
  - npm run coverage

cache:
  yarn: true
  directories:
    - "node_modules"
