language: node_js

node_js:
  - "node"
  - "7"
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g react-scripts

script:
  - react-scripts build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}

cache:
  yarn: true
  directories:
    - "node_modules"
