language: node_js

node_js:
  - "node"
  - "7"
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g react-scripts
  - npm install -g coveralls

script:
  - react-scripts build
  - react-scripts test
  - npm test -- --coverage && cat ./coverage/lcov.info | coveralls

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}

cache:
  yarn: true
  directories:
    - "node_modules"
